#!/usr/bin/python

import base64
import json
import os

relationships = json.loads(base64.b64decode(os.getenv('PLATFORM_RELATIONSHIPS')))
tomcat_rel = relationships['tomcat'][0]

print "http://%s" % tomcat_rel['host']
